name: Deploy on Localhost

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Start server
      run: |
        cd build
        python3 -m http.server 8080 --bind 127.0.0.1
    - name: Wait for server to start
      run: |
        while [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080)" != "200" ]; do sleep 5; done
    - name: Open browser
      if: runner.os == 'Windows'
      run: start http://localhost:8080/index.html
    - name: Open browser
      if: runner.os != 'Windows'
      run: open http://localhost:8080/index.html
